artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1f7X0BJ_yMnw4aCTcb00TO7ojw-uKjAGu/view?usp=sharing
  local_data_file: artifacts/data_ingestion/email_classification.zip
  unzip_dir: artifacts/data_ingestion